// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb_2x4yXpWRAkHCZJ7empCaeFjieeNddw',
    appId: '1:1017238286394:web:93f68d8b99cceed31d0503',
    messagingSenderId: '1017238286394',
    projectId: 'cheque-manager-cf7c3',
    authDomain: 'cheque-manager-cf7c3.firebaseapp.com',
    storageBucket: 'cheque-manager-cf7c3.firebasestorage.app',
    measurementId: 'G-YR4MLJTYPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD-n16RspJ659Dho-_XYrKGCnxcOEg_44',
    appId: '1:1017238286394:android:81c62f02cf678e061d0503',
    messagingSenderId: '1017238286394',
    projectId: 'cheque-manager-cf7c3',
    storageBucket: 'cheque-manager-cf7c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVB98J4HEo2xXwJ0JeLmDaA6RQRrMMs4w',
    appId: '1:1017238286394:ios:13d78071b7eb51e31d0503',
    messagingSenderId: '1017238286394',
    projectId: 'cheque-manager-cf7c3',
    storageBucket: 'cheque-manager-cf7c3.firebasestorage.app',
    iosBundleId: 'com.example.chequeManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVB98J4HEo2xXwJ0JeLmDaA6RQRrMMs4w',
    appId: '1:1017238286394:ios:13d78071b7eb51e31d0503',
    messagingSenderId: '1017238286394',
    projectId: 'cheque-manager-cf7c3',
    storageBucket: 'cheque-manager-cf7c3.firebasestorage.app',
    iosBundleId: 'com.example.chequeManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb_2x4yXpWRAkHCZJ7empCaeFjieeNddw',
    appId: '1:1017238286394:web:685d38f3869ac6371d0503',
    messagingSenderId: '1017238286394',
    projectId: 'cheque-manager-cf7c3',
    authDomain: 'cheque-manager-cf7c3.firebaseapp.com',
    storageBucket: 'cheque-manager-cf7c3.firebasestorage.app',
    measurementId: 'G-71L3069HHS',
  );
}
